name: Build and Test

on: 
  push:
    branches:  [main]
  pull_request:
    branches: [main]

jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: build -t vue-app .

      - name: build image
        run: build -t vue-app .

      - name: run image
        run: docker run -p 8080:80 vue-app

        
   
