name: Test

on: 
  workflow_dispatch: 
  pull_request:  
    branches: [main]
  push:
    branches: [main]

   
jobs:

  trivy_scan:
    runs-on: ubuntu-latest
    steps: 
    
      - name: checkout code
        uses: actions/checkout@v4
  
      - name: Run Trivy vulnerability scanner 
        uses: aquasecurity/trivy-action@master
        with: 
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'results.sarif'
          severity: 'CRITICAL'
  
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'results.sarif'


    
  build_and_upload_image:
    needs: [trivy_scan]

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: artimus47/iclass
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



  trivy_image_scan:
    needs: [build_and_upload_image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull artimus47/images:iclass

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'artimus47/images:iclass'
          format: 'sarif'
          output: 'image-results.sarif'
          severity: 'CRITICAL'
          
      - name: Upload Trivy scan results to Gmail
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Trivy Scan Results
          body: Attached are the Trivy scan results.
          to: artimusfowl5@gmail.com
          attachments: |
            image-results.sarif
            results.sarif
