name: Build and Test

on: 
  push:
    branches:  [main]
  pull_request:
    branches: [main]

jobs:
  build: 

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: install node-js
        uses: actions/node-js@v3
        
      - name: build image
        run: docker build -t vue-app .

        
   
